#!/bin/bash

source `dirname ${BASH_SOURCE[0]}`/config.sh

echo "::group::Configure yml env"
  echo "ARCH=$ARCH" >> $GITHUB_ENV
  echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
  echo "CRT=$CRT" >> $GITHUB_ENV
  echo "BINUTILS_REPO=$BINUTILS_REPO" >> $GITHUB_ENV
  echo "BINUTILS_BRANCH=$BINUTILS_BRANCH" >> $GITHUB_ENV
  echo "GCC_REPO=$GCC_REPO" >> $GITHUB_ENV
  echo "GCC_BRANCH=$GCC_BRANCH" >> $GITHUB_ENV
  echo "MINGW_REPO=$MINGW_REPO" >> $GITHUB_ENV
  echo "MINGW_BRANCH=$MINGW_BRANCH" >> $GITHUB_ENV
  echo "CYGWIN_REPO=$CYGWIN_REPO" >> $GITHUB_ENV
  echo "CYGWIN_BRANCH=$CYGWIN_BRANCH" >> $GITHUB_ENV
  echo "CYGWIN_PACKAGES_REPO=$CYGWIN_PACKAGES_REPO" >> $GITHUB_ENV
  echo "CYGWIN_PACKAGES_BRANCH=$CYGWIN_PACKAGES_BRANCH" >> $GITHUB_ENV
  echo "COCOM_REPO=$COCOM_REPO" >> $GITHUB_ENV
  echo "COCOM_BRANCH=$COCOM_BRANCH" >> $GITHUB_ENV
  echo "SOURCE_PATH=$SOURCE_PATH" >> $GITHUB_ENV
  echo "BUILD_PATH=$BUILD_PATH" >> $GITHUB_ENV
  echo "CCACHE_DIR_PATH=$CCACHE_DIR_PATH" >> $GITHUB_ENV
  echo "CCACHE=$CCACHE" >> $GITHUB_ENV
  echo "DELETE_BUILD=$DELETE_BUILD" >> $GITHUB_ENV
  echo "PACK_TOOLCHAIN=$PACK_TOOLCHAIN" >> $GITHUB_ENV
  echo "RELATIVE_ARTIFACT_PATH=./artifact" >> $GITHUB_ENV
  echo "TOOLCHAIN_ARTIFACT_NAME=$TOOLCHAIN_NAME-toolchain" >> $GITHUB_ENV
  echo "TOOLCHAIN_PACKAGE_NAME=$TOOLCHAIN_NAME-toolchain.tar.gz" >> $GITHUB_ENV
  echo "RUNTIME_ARTIFACT_NAME=$TOOLCHAIN_NAME-runtime" >> $GITHUB_ENV
  echo "RUNTIME_PACKAGE_NAME=$TOOLCHAIN_NAME-runtime.tar.gz" >> $GITHUB_ENV
  echo "TESTS_ARTIFACT_NAME=$TOOLCHAIN_NAME-tests" >> $GITHUB_ENV
  echo "TESTS_PACKAGE_NAME=$TOOLCHAIN_NAME-tests.tar.gz" >> $GITHUB_ENV
  echo "BUILD_ARTIFACT_NAME=$TOOLCHAIN_NAME-build" >> $GITHUB_ENV
echo "::endgroup::"
