set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM64)

set(CMAKE_AR aarch64-w64-mingw32-gcc-ar)
set(CMAKE_C_COMPILER aarch64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER aarch64-w64-mingw32-g++)
set(CMAKE_RANLIB aarch64-w64-mingw32-ranlib)
set(CMAKE_RC_COMPILER aarch64-w64-mingw32-windres)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")

if(NOT DEFINED CMAKE_BUILD_TYPE)
    message(STATUS "No Build Type specified. Defaulting to Release.")
    set(CMAKE_BUILD_TYPE "Release")
endif()

if (NOT DEFINED CMAKE_INTERPROCEDURAL_OPTIMIZATION)
  if (CMAKE_BUILD_TYPE STREQUAL "Release")
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF)
  endif()
endif()

message(STATUS "Build Type: " ${CMAKE_BUILD_TYPE})
message(STATUS "IPO/LTO is " "${CMAKE_INTERPROCEDURAL_OPTIMIZATION}")

string(REPLACE "-fvisibility=hidden" "" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
string(REPLACE "-fvisibility=hidden" "" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
